import type { Metadata } from "next"
import { Noto_Sans } from 'next/font/google'
import "./globals.css"
import { cn } from "@/lib/utils"

const fontSans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang={'en'} suppressHydrationWarning>
      <body
        className={cn('min-h-screen scroll-smooth font-sans antialiased bg-background', fontSans.variable)}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
